### ISSUE TITLE
Script Not Working Because of CORS

### ISSUE THREAD

**Issue by singhashwin27** [GeekyBharat99/instagram-video-downloader#5]
Hey, 

Recently the script has stopped working because of CORS issues. Any way to get it up and running again? Can we use something like the proxy domain to bypass cors restrictions

**Comment by GeekyBharat99** [comment]
hello ashwin, i m not in the mood to update this repository now.. you can use this "?__a=1" this is instagram's official API.. which throws json of any post if this "?__a=1" is included in the URL. hope u got this. if not google it about "?__a=1" this thing.
